/**
 * In-memory domain index loaded from bundled snapshot.
 * Replaces Supabase/charity API for .skr SeekerID data.
 *
 * Snapshot path: data/seeker-domains.jsonl.gz (generated by scripts/export-domains.py)
 * Optional live path: try Turso if TURSO_DOMAINS_RW is set (future).
 */
import { gunzipSync } from "zlib";
import { readFileSync, existsSync } from "fs";
import path from "path";
import { DomainInfo } from "../constantTypes";

export type DomainRecord = {
  rank: number;
  domain: string;
  subdomain: string;
  owner: string;
  created_at: string;
};

type Index = {
  rows: DomainRecord[];
  bySubdomain: Map<string, DomainRecord>;
  byOwner: Map<string, DomainRecord[]>;
  domainsByDate: Record<string, number>;
  domainsByTimeRange: Record<string, number>;
  loadedAt: number;
};

let index: Index | null = null;

function snapshotPath(): string {
  // Prefer project data/ (not public — large binary)
  const candidates = [
    path.join(process.cwd(), "data", "seeker-domains.jsonl.gz"),
    path.join(process.cwd(), "public", "data", "seeker-domains.jsonl.gz"),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return candidates[0];
}

function loadIndex(): Index {
  if (index) return index;

  const file = snapshotPath();
  if (!existsSync(file)) {
    console.error("Domain snapshot missing:", file);
    index = {
      rows: [],
      bySubdomain: new Map(),
      byOwner: new Map(),
      domainsByDate: {},
      domainsByTimeRange: {},
      loadedAt: Date.now(),
    };
    return index;
  }

  const raw = gunzipSync(readFileSync(file)).toString("utf8");
  const rows: DomainRecord[] = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      rows.push(JSON.parse(line) as DomainRecord);
    } catch {
      /* skip bad line */
    }
  }

  // Rank ascending in export; keep as-is for stable rank lookups
  const bySubdomain = new Map<string, DomainRecord>();
  const byOwner = new Map<string, DomainRecord[]>();
  const domainsByDate: Record<string, number> = {};
  const hourCounts = new Array(24).fill(0);

  for (const r of rows) {
    bySubdomain.set(r.subdomain.toLowerCase(), r);
    const list = byOwner.get(r.owner) || [];
    list.push(r);
    byOwner.set(r.owner, list);

    const day = r.created_at.slice(0, 10);
    domainsByDate[day] = (domainsByDate[day] || 0) + 1;

    if (r.created_at.length >= 13) {
      const h = parseInt(r.created_at.slice(11, 13), 10);
      if (h >= 0 && h < 24) hourCounts[h]++;
    }
  }

  // Prefer shorter names first within owner lists
  for (const [owner, list] of byOwner) {
    list.sort((a, b) => a.subdomain.length - b.subdomain.length);
    byOwner.set(owner, list);
  }

  const sum = (a: number, b: number) =>
    hourCounts.slice(a, b).reduce((s, n) => s + n, 0);

  index = {
    rows,
    bySubdomain,
    byOwner,
    domainsByDate,
    domainsByTimeRange: {
      "0-6": sum(0, 6),
      "6-12": sum(6, 12),
      "12-18": sum(12, 18),
      "18-24": sum(18, 24),
    },
    loadedAt: Date.now(),
  };
  console.log(`Domain index loaded: ${rows.length} rows from ${file}`);
  return index;
}

export function recordToDomainInfo(r: DomainRecord): DomainInfo {
  return {
    domain: r.domain || ".skr",
    subdomain: r.subdomain,
    created_at: r.created_at,
    subdomain_tx: "",
    subdomain_tx_blocktime: r.created_at,
    name_account: "",
    tld_account: "",
    owner: r.owner,
    rank: r.rank,
    non_transferable: false,
  };
}

export type ListParams = {
  page?: number;
  pageSize?: number;
  sortBy?: "newest" | "oldest" | "name" | "name-reverse" | "length";
  query?: string;
  rank?: number;
  beforeTimestamp?: string | null;
};

export function listDomains(params: ListParams = {}) {
  const idx = loadIndex();
  const page = Math.max(1, params.page ?? 1);
  const pageSize = Math.min(200_000, Math.max(1, params.pageSize ?? 50));
  const sortBy = params.sortBy ?? "newest";
  const query = (params.query || "").trim().toLowerCase();
  const rank = params.rank;
  const before = params.beforeTimestamp;

  let filtered = idx.rows;
  if (query || rank || before) {
    filtered = idx.rows.filter((r) => {
      if (query && !r.subdomain.toLowerCase().includes(query)) return false;
      if (rank != null && Number.isFinite(rank) && r.rank !== rank) return false;
      if (before && r.created_at > before) return false;
      return true;
    });
  }

  const sorted = [...filtered];
  switch (sortBy) {
    case "oldest":
      sorted.sort(
        (a, b) =>
          a.created_at.localeCompare(b.created_at) || a.rank - b.rank
      );
      break;
    case "name":
      sorted.sort((a, b) => a.subdomain.localeCompare(b.subdomain));
      break;
    case "name-reverse":
      sorted.sort((a, b) => b.subdomain.localeCompare(a.subdomain));
      break;
    case "length":
      sorted.sort(
        (a, b) =>
          a.subdomain.length - b.subdomain.length ||
          a.subdomain.localeCompare(b.subdomain)
      );
      break;
    case "newest":
    default:
      sorted.sort(
        (a, b) =>
          b.created_at.localeCompare(a.created_at) || b.rank - a.rank
      );
      break;
  }

  const total = sorted.length;
  const offset = (page - 1) * pageSize;
  const pageRows = sorted.slice(offset, offset + pageSize);

  return {
    success: true as const,
    message: "Fetched domains successfully",
    pagination: {
      total,
      page,
      pageSize,
      totalPages: Math.max(1, Math.ceil(total / pageSize)),
    },
    totalDomains: idx.rows.length,
    domainsByDate: idx.domainsByDate,
    domainsByTimeRange: idx.domainsByTimeRange,
    data: pageRows.map(recordToDomainInfo),
  };
}

export function getDomainByName(name: string): DomainRecord | null {
  const idx = loadIndex();
  let raw = name.trim().toLowerCase();
  if (raw.endsWith(".skr")) raw = raw.slice(0, -4);
  if (raw.startsWith(".")) raw = raw.slice(1);
  return idx.bySubdomain.get(raw) || null;
}

export function getDomainsByOwner(wallet: string): DomainRecord[] {
  return loadIndex().byOwner.get(wallet) || [];
}

export function getOwnerToShortestSubdomain(): Map<string, string> {
  const idx = loadIndex();
  const m = new Map<string, string>();
  for (const [owner, list] of idx.byOwner) {
    if (list[0]) m.set(owner, list[0].subdomain);
  }
  return m;
}

export function domainStats() {
  const idx = loadIndex();
  return {
    total: idx.rows.length,
    domainsByDate: idx.domainsByDate,
    domainsByTimeRange: idx.domainsByTimeRange,
    loadedAt: idx.loadedAt,
  };
}
